### UAT环境配置
spring:
  application:
    name: base-microservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/zuul-server
    username: root
    password: zhanwei
  cloud:
    consul:
      host: 121.42.143.130
      port: 8500
      enabled: true
      discovery:
        health-check-path: ${server.servlet.context-path}/actuator/health
        prefer-ip-address: true
        ip-address: localhost

cassandra:
  host: 118.31.46.174
  port: 9042
  keyspace: demo